# Generated by Django 5.2.17 on 2026-08-30 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('MANUTENCAO', 'Manutenção')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação'), ('INICIO', 'Início'), ('ATUALIZACAO', 'Atualização'), ('CONCLUSAO', 'Conclusão')], max_length=12)),
                ('informacao', models.TextField(blank=True)),
                ('status_relacionado', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.chamado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_autoria', to='chamados.perfildemo')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsaveis', to='chamados.perfildemo'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_solicitados', to='chamados.perfildemo'),
        ),
    ]
